[project]
name = "virtual-reactor"
version = "0.1.0"
description = "A Python library for modeling and simulating chemical reactors."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["src"]